# Site settings
title: "Ash Bhimasani"
page_title: "Ash Bhimasani - Artist & Maker"
email: 16abhimasani@gmail.com
description: "Ash Bhimasani is a multimedia artist and maker from Philadelphia."

# Server
baseurl: ""
destination: _site
host: 0.0.0.0
port: 4001
url: http://ash.bhimasani.com
encoding: UTF-8

# Excludes
exclude: ["node_modules", "Gemfile", "Gemfile.lock", "commit-hook.sh", "package.json"]

# URLs
permalink: pretty

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Repo
repo: https://github.com/16abhimasani/16abhimasani.github.io
